name: Build backend and frontend

on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v5.0.1
        with: 
          go-version: "1.22"
      - name: "install packages"
        run: go mod download
      - name: "build backend"
        run: go build backend/main.go

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: "install yarn"
        run: npm i yarn
      - name: "install packages"
        run: yarn install
      - name: "build frontend"
        run: CI=false yarn build
  
